name: Compilation et déploiement Laravel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer les dépendances PHP
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Installer les dépendances npm
        run: npm install

      - name: Build
        run: npm run build

      - name: Compiler le code Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize --force

      - name: Déployer vers le serveur
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/myshop
          overwrite: true
