name: Compilation et déploiement Laravel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer les dépendances PHP
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Installer les dépendances npm
        run: npm install

      - name: Build
        run: npm run build

      - name: Déployer vers le serveur
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: jsprod.fr
          username: u957733266
          password: Azerty972
          local-dir: ./
          server-dir: /public_html/myshop/
